from __future__ import annotations

import html
import json
import os
import re
import signal
import socket
import subprocess
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
HOST_DEMO_ROOT = PROJECT_ROOT / "tmp" / "host-demo-backends"
HOST_DEMO_LOG_DIR = PROJECT_ROOT / "tmp" / "logs"
HOST_DEMO_RUNTIME_DIR = PROJECT_ROOT / ".runtime" / "host-demo-backends"


def extract_port_from_upstream(value: Any) -> int | None:
    text = str(value or "").strip()
    text = text.replace("http://", "").replace("https://", "").rstrip("/")

    match = re.search(r":(\d+)$", text)
    if not match:
        return None

    port = int(match.group(1))

    if 1 <= port <= 65535:
        return port

    return None


def extract_demo_backend_ports(config: dict[str, Any]) -> list[int]:
    """
    Extract every backend port from config.

    Supports:
      {"upstream": "host.docker.internal:9000"}
      {"upstream": "host.docker.internal:9101,host.docker.internal:9102"}
      {"upstreams": ["host.docker.internal:9101", "host.docker.internal:9102"]}
      {"upstreams": [{"address": "host.docker.internal:9101"}]}
    """
    ports: list[int] = []

    routes = config.get("routes") or []

    if not isinstance(routes, list):
        return ports

    for route in routes:
        if not isinstance(route, dict):
            continue

        candidates: list[Any] = []

        for key in ("upstream", "backend", "target"):
            value = route.get(key)
            if value:
                candidates.append(value)

        upstreams = route.get("upstreams")
        if isinstance(upstreams, list):
            for item in upstreams:
                if isinstance(item, dict):
                    candidates.append(
                        item.get("address")
                        or item.get("upstream")
                        or item.get("backend")
                    )
                else:
                    candidates.append(item)

        for candidate in candidates:
            for part in str(candidate or "").split(","):
                port = extract_port_from_upstream(part)
                if port and port not in ports:
                    ports.append(port)

    return ports


def is_port_open(port: int, host: str = "127.0.0.1", timeout: float = 0.25) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def host_demo_backend_dir(port: int) -> Path:
    return HOST_DEMO_ROOT / str(port)


def host_demo_backend_pid_file(port: int) -> Path:
    return HOST_DEMO_RUNTIME_DIR / f"backend-{port}.pid"


def host_demo_backend_log_file(port: int) -> Path:
    return HOST_DEMO_LOG_DIR / f"backend-{port}.log"


def write_host_demo_backend_files(port: int) -> Path:
    backend_dir = host_demo_backend_dir(port)
    backend_dir.mkdir(parents=True, exist_ok=True)

    index_path = backend_dir / "index.html"
    health_path = backend_dir / "health.json"

    index_path.write_text(
        f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Demo Backend {port}</title>
</head>
<body>
  <h1>✅ Demo Backend {port}</h1>
  <p>This response came from backend port <strong>{port}</strong>.</p>
  <p>Generated by AI Pingora Gateway.</p>
</body>
</html>
""",
        encoding="utf-8",
    )

    health_path.write_text(
        json.dumps(
            {
                "status": "ok",
                "backend_port": port,
                "generated_by": "AI Pingora Gateway demo backend writer",
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    return backend_dir


def start_host_demo_backend(
    port: int,
    *,
    bind_host: str = "0.0.0.0",
) -> dict[str, Any]:
    """
    Starts a real Python webserver for docker_host testing.

    bind_host is 0.0.0.0 so Docker containers can reach the host backend via:
      host.docker.internal:PORT
    """
    HOST_DEMO_RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    HOST_DEMO_LOG_DIR.mkdir(parents=True, exist_ok=True)

    if is_port_open(port):
        return {
            "port": port,
            "status": "already_running",
            "started": False,
            "url": f"http://127.0.0.1:{port}/",
        }

    backend_dir = write_host_demo_backend_files(port)
    log_path = host_demo_backend_log_file(port)

    log_handle = log_path.open("a", encoding="utf-8")

    process = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "http.server",
            str(port),
            "--bind",
            bind_host,
            "--directory",
            str(backend_dir),
        ],
        stdout=log_handle,
        stderr=subprocess.STDOUT,
        cwd=str(PROJECT_ROOT),
        start_new_session=True,
    )

    host_demo_backend_pid_file(port).write_text(str(process.pid), encoding="utf-8")

    return {
        "port": port,
        "status": "started",
        "started": True,
        "pid": process.pid,
        "url": f"http://127.0.0.1:{port}/",
        "bind_host": bind_host,
        "directory": str(backend_dir),
        "log": str(log_path),
    }


def stop_host_demo_backend(port: int) -> dict[str, Any]:
    pid_path = host_demo_backend_pid_file(port)

    if not pid_path.exists():
        return {
            "port": port,
            "status": "not_managed",
            "stopped": False,
        }

    try:
        pid = int(pid_path.read_text(encoding="utf-8").strip())
    except Exception:
        pid_path.unlink(missing_ok=True)
        return {
            "port": port,
            "status": "bad_pid_file",
            "stopped": False,
        }

    try:
        os.killpg(pid, signal.SIGTERM)
    except ProcessLookupError:
        pass
    except Exception:
        try:
            os.kill(pid, signal.SIGTERM)
        except Exception:
            pass

    pid_path.unlink(missing_ok=True)

    return {
        "port": port,
        "status": "stopped",
        "stopped": True,
        "pid": pid,
    }


def ensure_host_demo_backend_servers(
    config: dict[str, Any],
    *,
    bind_host: str = "0.0.0.0",
) -> dict[str, Any]:
    ports = extract_demo_backend_ports(config)

    results = [
        start_host_demo_backend(port, bind_host=bind_host)
        for port in ports
    ]

    return {
        "ports": ports,
        "started": [
            item for item in results if item.get("status") == "started"
        ],
        "already_running": [
            item for item in results if item.get("status") == "already_running"
        ],
        "results": results,
    }


def stop_host_demo_backend_servers(config: dict[str, Any]) -> dict[str, Any]:
    ports = extract_demo_backend_ports(config)

    results = [
        stop_host_demo_backend(port)
        for port in ports
    ]

    return {
        "ports": ports,
        "results": results,
    }